### ISSUE TITLE
VDatum MCU in Products 2 and 3

### ISSUE THREAD

**Issue by stephen-a-white** [noaa-rsd/LiProd#26]
https://github.com/noaa-rsd/LiProd/blob/0f4209e08ca5637f6243966554b12097d7d5fbb1/support_files/library.json#L21

Looks like the VDatum MCU is hard coded as "8.96 centimeters".  Do we want to utilize the actual uncertainty values coming out of VDatum or from an MCU lookup table?

**Comment by gimahori** [comment]
I think using the actual uncertainty values makes sense (unless there is some difficulty with doing that).

**Comment by forkozi** [comment]
@stephen-a-white, by lookup table, do you mean listing the mcu values for each region?  

What about when the day comes that we have spatially varying MCU (or something) within each region?  What if, instead of listing individual values, we reference https://vdatum.noaa.gov/docs/est_uncertainties.html?

(or...we could go hog wild and include a 4th band in the product definition...the uncertainty of the vertical transformation.  i know that might be a bit too crazy though!)

**Comment by stephen-a-white** [comment]
Yep, that was what I meant, just a list.  I am good with referencing the web page.

That is a good idea.  It would be cool to have a 4th (maybe separation surface) and 5th (maybe separation surface uncertainty) bands in the future when SVU becomes a little more consistent.  Would increase data size, but would be nice to have.  Will have to keep that idea as a possibility in the future.

**Comment by forkozi** [comment]
Roger that.  For now, just referencing the web page.
