### ISSUE TITLE
FL1606 crashed

### ISSUE THREAD

**Issue by gimahori** [noaa-rsd/LiProd#39]
I got this in the cmd window when I selected the + next to the project number for FL1606:
![image](https://user-images.githubusercontent.com/44785008/92049267-f4030e00-ed57-11ea-80fc-e3a0f1cef253.png)

[config.zip](https://github.com/noaa-rsd/LiProd/files/5165423/config.zip)

I have attached the config file... also is it possible that the las dir string is too long?  
thx,
g

**Comment by forkozi** [comment]
Did you have other instances of LiPROD open, by chance?   I've seen errors like this, involving mentions of "pipes," when intentionally exiting the program while multiprocessing things are happening, but it's weird it happened just when initializing LiPROD.  Did the initialization start at all (i.e., did you see any of the progress bar), or did it immediately give you the error?  I just initialized the same survey, with a local tracker file (for troubleshooting purposes) and it initialized successfully.   Did you try it a second time?  If not, can you give it another whirl, and see what happens?

**Comment by gimahori** [comment]
just crashed again and I had run 1608 earlier which was fine

![image](https://user-images.githubusercontent.com/44785008/92119946-6ca0b380-edc6-11ea-81f6-f9ff196de949.png)

Tried a few things but it still crashed - config file is attached.

[config.zip](https://github.com/noaa-rsd/LiProd/files/5168854/config.zip)

**Comment by forkozi** [comment]
For now, how about closing LiPROD between surveys.   Does that work?   I'll try to figure out what's happening...

**Comment by gimahori** [comment]
I did that for FL1606 twice or three times and it crashed. Its now working on FL1808

**Comment by gimahori** [comment]
Thank you Nick! I mapped the drive and drilled down to the last sub folder and FL1606 working now :)

**Comment by forkozi** [comment]
Your hunch was dead on, Gretchen.  I'm only just learning about this, but it appears that the path of the las file was too long...by a mere 3 characters!    Here are a couple references describing Microsofts MAX_PATH setting (which, because of legacy issues, defaults to 260 characters, even though NTFS can support up to 65,535 characters) ...

- https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
- https://www.jam-software.com/treesize/search_long_paths.shtml#:~:text=While%20Windows'%20standard%20file%20system,value%20of%20the%20constant%20MAX_PATH.

I believe this is why it works with specifying the path with a mapped drive versus the full UNC. 

As for how to deal with this in general...I'm not sure.  For now, using the mapped path seems to work, but even that might pose issues in the future if we have some project whoppers with long file names.
