### ISSUE TITLE
gaps/artifacts in FL1604 data 

### ISSUE THREAD

**Issue by gimahori** [noaa-rsd/LiProd#41]
Hi,

I have been QC'ing few surveys now that all the surveys have been run through the latest version of LiPROD and I found gaps /artifacts in FL1604 but not in FL1605 or others so far. 

![image](https://user-images.githubusercontent.com/44785008/93133663-93ec6000-f6a5-11ea-9f1f-07c9e4b5224b.png)

Nick is looking into. I thought this was a problem with maybe ArcPro but opened this in ArcMap and the artifacts are showing up there too. I am going to re-run this survey just in case something happened while it was running.
thx,
g

**Comment by forkozi** [comment]
I know we talked about this yesterday, but could you verify that the tif's were generated with v1.1.0?  I just ran the Marco Island project through LiPROD (locally), and there are no gap artifacts (there's the expected area of overlap).  Perhaps it's because of the pathname anomalies in the tracker file?  Were any previously generated products moved to another network location after being generated?

**Comment by gimahori** [comment]
Yea it says it was in the project tracker from 9/1 that I saved in the archive that I used version 1.1.0

![image](https://user-images.githubusercontent.com/44785008/93366713-822bc980-f819-11ea-949a-c86afcd730dd.png)

But I looked at the FL1604 I ran last night and it looks like there aren't gaps so I'm not sure what happened.  I guess its good the gaps are gone tho!  That was a big concern. I'm going to close this out since I don't see this issue in the other FL surveys.
